name: 'Setup conch action rust kit'
description: 'Setup conch action rust kit'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Setup Protoc
      shell: bash
      run: |
        echo "~/ci/third_party/protoc-22.0-linux-x86_64/bin" >> $GITHUB_PATH
    - name: Cache Crates
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: conch-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          conch-${{ runner.os }}-${{ hashFiles('Cargo.lock') }}
          conch-${{ runner.os }}
